### ISSUE TITLE
RethinkDB remote connection

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/role_rethinkdb#1]
You should solve below solution for remote connection
1. Allow all [remote connection](https://rethinkdb.com/docs/administration-tools/)
2. [Set username and password](https://rethinkdb.com/docs/permissions-and-accounts)
3. [Connection by username & password](https://rethinkdb.com/api/python/connect/)

**Comment by qiaofeng1227** [comment]
## The accurate solution for remote

1. Edit /etc/rethinkdb/instances.d/instance.conf, set `#bind=*` to `bind=0.0.0.0`
2. Restart RethinkDB
   ```
   systemctl restart rethinkdb
   ```

**Comment by qiaofeng1227** [comment]
defaults/main.yml
```
rethinkdb_admin_username: "admin"
rethinkdb_admin_password: "123456"
```

main.yml 
```
- name: Install rethinkdb connect tool
  pip: 
    name: rethinkdb
    executable: pip3

- name: Install rethinkdb connect tool
  shell: |
    echo  "r.db('rethinkdb').table('users').get('admin').update({'password': {{rethinkdb_admin_password}}'}).run()" | rethinkdb-repl
```
